# Generated by Django 2.0.7 on 2020-09-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_turma'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='turma',
            managers=[
            ],
        ),
    ]
