# Generated by Django 2.0.7 on 2020-09-24 22:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200924_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Funcionarios',
        ),
        migrations.RenameModel(
            old_name='Turma',
            new_name='Turmas',
        ),
        migrations.AlterModelManagers(
            name='funcionarios',
            managers=[
                ('funcionarios', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='turmas',
            managers=[
                ('turmas', django.db.models.manager.Manager()),
            ],
        ),
    ]
