# Generated by Django 2.0.7 on 2020-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.IntegerField(max_length=55),
        ),
    ]
