# Generated by Django 2.0.7 on 2020-09-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200918_2149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientes',
            managers=[
            ],
        ),
    ]
