# Generated by Django 2.0.7 on 2020-09-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200924_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
