# Generated by Django 2.0.7 on 2020-09-19 00:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.IntegerField(max_length=55)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            managers=[
                ('empresas', django.db.models.manager.Manager()),
            ],
        ),
    ]
