# Generated by Django 2.0.7 on 2020-09-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='empresas',
            managers=[
            ],
        ),
    ]
